service: lovebox-lambda

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev

functions:
    sendNote:
        handler: dist/lovebox.sendNote

package:
    exclude:
        - node_modules/typescript/**
        - node_modules/@types/**
