service: lovebox-lambda

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:${self:provider.region}:*"

functions:
    sendNote:
        handler: dist/lovebox.sendNote

package:
    exclude:
        - node_modules/typescript/**
        - node_modules/@types/**
