service: lovebox-lambda

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:${self:provider.region}:*"
        - Effect: "Allow"
          Action:
              - "s3:ListBucket"
              - "s3:GetObject"
          Resource: "arn:aws:s3:::lovebox-stash/*"

functions:
    sendNote:
        handler: dist/lovebox.sendNote
        events:
            - schedule: rate(1 day)

package:
    exclude:
        - node_modules/typescript/**
        - node_modules/@types/**
